# permissions for end users to view hardwareclassifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hardwareclassification-viewer-role
rules:
- apiGroups:
  - metal3.metal3.io
  resources:
  - hardwareclassifications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.metal3.io
  resources:
  - hardwareclassifications/status
  verbs:
  - get
